package org.example;

import com.google.gson.Gson;
import lombok.Getter;
import org.example.Entity.ObjectDTO;
import org.example.Entity.TypeObjectDTO;
import org.example.Services.GsonFactory;
import org.example.Services.MyCanvas;
import org.example.Services.MyThread;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

/**
 * @author egorm
 */

public class MainFrame extends javax.swing.JFrame {
    private final MyThread myThread;
    public static Socket socket;
    public static String name;
    public static Color color;
    private BufferedReader in;
    private PrintWriter out;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        canvas1.setBackground(Color.lightGray);
        myThread = new MyThread(canvas1);
        try {
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            out = new PrintWriter(socket.getOutputStream(), true);
            myThread.setIn(in);
            myThread.setOut(out);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        this.player1.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        ready = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        cont = new javax.swing.JButton();
        score = new javax.swing.JButton();

        jlabel1 = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        countShot1 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        countShot2 = new javax.swing.JLabel();
        shot = new javax.swing.JButton();
        canvas1 = new MyCanvas(this, 4, 3, countShot1, countShot2, score1, score2);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ready.setText("Готов");
        ready.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readyMouseClicked(evt);
            }
        });
        shot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shotClicked(evt);
            }
        });
        stop.setText("Остановить");
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopClicked(evt);
            }
        });
        stop.setEnabled(false);
        cont.setText("Продолжить");
        cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myThread.setStart(true);
                stop.setEnabled(true);
                cont.setEnabled(false);
            }
        });
        score.setText("Таблица игроков");
        score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new ScoreTable().setVisible(true);
            }
        });
//        score.setEnabled(false);
        jlabel1.setText("Игрок");

        player1.setText("player1");
        player1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel2.setText("Счет игрока");

//        score1.setText("score1");
        score1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel3.setText("Кол-во выстрелов");

//        countShot1.setText("score1");
        countShot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel4.setText("Игрок");

        player2.setText("player2");
        player2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel5.setText("Счет игрока");

//        score2.setText("score1");
        score2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabel6.setText("Кол-во выстрелов");

//        countShot2.setText("score1");
        countShot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        shot.setText("Выстрел");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(ready)
                                                .addGap(18, 18, 18)
                                                .addComponent(cont)
                                                .addGap(18, 18, 18)
                                                .addComponent(stop)
                                                .addGap(18, 18, 18)
                                                .addComponent(shot)
                                                .addGap(18, 18, 18)
                                                .addComponent(score))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(player1)
                                                        .addComponent(jlabel1)
                                                        .addComponent(score1)
                                                        .addComponent(jlabel2)
                                                        .addComponent(countShot1)
                                                        .addComponent(jlabel3)
                                                        .addComponent(player2)
                                                        .addComponent(jlabel4)
                                                        .addComponent(score2)
                                                        .addComponent(jlabel5)
                                                        .addComponent(countShot2)
                                                        .addComponent(jlabel6))))
                                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jlabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(player1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(score1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(countShot1)
                                                .addGap(44, 44, 44)
                                                .addComponent(jlabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(player2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(score2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jlabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(countShot2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ready)
                                        .addComponent(cont)
                                        .addComponent(stop)
                                        .addComponent(shot)
                                        .addComponent(score)
                                )
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readyMouseClicked(java.awt.event.MouseEvent evt) {
        ready.setEnabled(false);
        ObjectDTO objectDTO = new ObjectDTO(TypeObjectDTO.READY, name, "");
        Gson gson = GsonFactory.getInstance();
        String data = gson.toJson(objectDTO);
//        System.out.println("Send: " + data);
        out.println(data);

        try {
            String answer = in.readLine();
            objectDTO = gson.fromJson(answer, ObjectDTO.class);
            System.out.println(objectDTO);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        if (objectDTO != null && objectDTO.getType() == TypeObjectDTO.READY) {
            myThread.start();
            myThread.setStart(true);

            stop.setEnabled(true);
        }
    }

    private void stopClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        myThread.setStart(false);
        stop.setEnabled(false);
        ready.setEnabled(true);
        cont.setEnabled(true);

    }

    private void shotClicked(java.awt.event.MouseEvent evt) {
        myThread.setShot(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    private MyCanvas canvas1;

    private javax.swing.JLabel countShot1;
    @Getter
    private javax.swing.JLabel countShot2;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    @Getter
    private javax.swing.JLabel player1;
    @Getter
    private javax.swing.JLabel player2;
    private javax.swing.JButton ready;
    @Getter
    private javax.swing.JLabel score1;
    @Getter
    private javax.swing.JLabel score2;
    private javax.swing.JButton shot;
    private javax.swing.JButton stop;
    private javax.swing.JButton cont;
    private javax.swing.JButton score;

}
